version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
      - ./extensions:/directus/extensions
    environment:
      KEY: '80404fc5a25cf4be4233a65d492bfd70'
      SECRET: '936ecf44940910766f1d02b73b1d14a1'

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'

      ADMIN_EMAIL: 'viyanateaa@gmail.com'
      ADMIN_PASSWORD: '12345'

      # Make sure to set this in production

      # (see https://docs.directus.io/self-hosted/config-options#general)

      PUBLIC_URL: 'https://directus-user-abevv.apps.tocp4.arbetsformedlingen.se/'