apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: directus
  name: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: directus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: directus
    spec:
      containers:
        - env:
            - name: ADMIN_EMAIL
              value: viyan.ateaa@gmail.com
            - name: ADMIN_PASSWORD
              value: "12345"
            - name: DB_CLIENT
              value: sqlite3
            - name: DB_FILENAME
              value: ./database/data.db
            - name: KEY
              value: 80404fc5a25cf4be4233a65d492bfd70
            - name: PUBLIC_URL
              value: https://directus-user-abevv.apps.tocp4.arbetsformedlingen.se/
            - name: SECRET
              value: 936ecf44940910766f1d02b73b1d14a1
          image: directus/directus:latest
          name: directus
          ports:
            - containerPort: 8055
          resources: {}
          volumeMounts:
            - mountPath: /directus/uploads
              name: directus-claim0
            - mountPath: /directus/database
              name: directus-claim1
            - mountPath: /directus/extensions
              name: directus-claim2
      restartPolicy: Always
      volumes:
        - name: directus-claim0
          persistentVolumeClaim:
            claimName: directus-claim0
        - name: directus-claim1
          persistentVolumeClaim:
            claimName: directus-claim1
        - name: directus-claim2
          persistentVolumeClaim:
            claimName: directus-claim2
status: {}
